version: '3'
services:

  #PHP
  pass_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vivasoft/php:8.0
    container_name: pass_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./_source_/:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx
  pass_webserver:
    image: nginx:latest
    container_name: pass_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8020:80"
      - "44320:443"
    volumes:
      - ./_source_/:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx/:/var/log/nginx/
    networks:
      - app-network

  # Mongo Server
  pass_mongo:
    image: mongo:latest
    container_name: pass_mongo
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_DATABASE: pass
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - datadb:/data/db
    networks:
      - app-network

  # Mongo Server
  pass_mongo_express:
    image: mongo-express
    container_name: pass_mongo_express
    restart: always
    ports:
      - "8021:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: pass_mongo
      ME_CONFIG_BASICAUTH_USERNAME: vivasoft
      ME_CONFIG_BASICAUTH_PASSWORD: vivasoft
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - app-network

  #REDIS
  pass_redis:
    image: redis:latest
    container_name: pass_redis
    ports:
      - "63720:6379"
    networks:
      - app-network

  pass_mailhog:
    image: mailhog/mailhog
    container_name: pass_mailhog
    restart: always
    ports:
      - "10220:1025"
      - "60220:8025"
    networks:
      - app-network

#Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  datadb:
    driver: local
